urls.py
from django.urls import path
from django.views.generic.dates import ArchiveIndexView
from django.views.generic import ListView
from datetime import date

from .views import *
# from . import views
from .models import Announcement

app_name = 'announcements'

urlpatterns = [
    path('', AnnouncementMonthView.as_view(), name="show_announcements"),
    path('events/', EventMonthView.as_view(), name="show_events"),
    path('events/registration/edit/<int:pk>', EventRegistrationView.as_view(), name='event_registration_update'),
    path('events/registration/add/<int:pk>', event_add_attendance, name = 'event_registration_create'),

    path('list/', ListView.as_view(model=Announcement), name='announcement_list'),
    path('archive/', ArchiveIndexView.as_view(model=Announcement, date_field="announcement_date", allow_future=True), name="announcement_archive"),

    # NEEDS TO BE FIXED!!!!
    
    # Example: /2012/08/
    path('<int:year>/<int:month>/', AnnouncementMonthView.as_view(month_format='%m'), name="announcement_month_numeric"),
    # Example: /2012/aug/
    path('<int:year>/<str:month>/', AnnouncementMonthView.as_view(), name="announcement_month"),

    # Example: /2012/08/
    path('events/<int:year>/<int:month>/', EventMonthView.as_view(month_format='%m'), name="event_month_numeric"),
    # Example: /2012/aug/
    path('events/<int:year>/<str:month>/', EventMonthView.as_view(), name="event_month"),
]

models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Announcement(models.Model):
    title       = models.CharField(max_length = 100)
    desc        = models.TextField(
        help_text="IMPORTANT: Google will use this as a preview snippet in the results of search.",
        blank=True
    )
    pub_date    = models.DateField()             # Day Event is Posted (for newsletter)
    recurring   = models.BooleanField()          # If true, the event repeats every week

    #event_date  = models.DateField(blank=True, null=True)             # Day of the Event

    def __str__(self):
        return '%s announced %s' % (self.title, str(self.pub_date.strftime("%Y-%m-%d")))

    @property
    def media(self):
        return self.media_set.all()

class Event(models.Model):
    announcement    = models.OneToOneField(Announcement, on_delete=models.CASCADE)
    event_date      = models.DateField(blank=True, null=True)

    def __str__(self):
        return '%s' % self.announcement

    def add_user_to_list_of_attendees(self, user):
        registration = EventRegistration.objects.create(user = user, event = self)
        return registration.pk

    def get_absolute_url(self):
        # return reverse('announcements:event_registration_create', args=[self.event])
        return reverse('announcements:event_registration_create', kwargs={'pk': self.pk})

class EventRegistration(models.Model):
    event   = models.ForeignKey(Event, on_delete=models.CASCADE)
    user    = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Attendee')
    number  = models.IntegerField(verbose_name='Number of Guests', default=1)
    note   = models.TextField(blank = True)

    class Meta:
        unique_together = ['event', 'user']

    def __str__(self):
        return self.user.username

class Media(models.Model):
    file_name       = models.CharField(max_length = 50)
    announcement    = models.ForeignKey(Announcement, on_delete=models.CASCADE)
    desc            = models.TextField(blank = True)
    position        = models.IntegerField(blank=True)

    def __str__(self):
        return self.file_name

forms.py
from django import forms
from django.forms import ModelForm, TextInput
from .models import EventRegistration

class EventRegistrationForm(ModelForm):
    required_css_class = 'required'
    class Meta:
        model = EventRegistration
        fields = '__all__'

views.py
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.utils.timezone import now
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

from django.views.generic.dates import ArchiveIndexView, MonthArchiveView
from django.views.generic import CreateView, UpdateView

from .models import Announcement, Event, EventRegistration
from .forms import EventRegistrationForm

# Create your views here.
# class EventArchiveIndexView(ArchiveIndexView):
#     model = Event
#     date_field = 'event_date'

class AnnouncementMonthView(MonthArchiveView):
    def get_month(self):
        try:
            month = super(AnnouncementMonthView, self).get_month()
        except Http404:
            month = now().strftime(self.get_month_format())
        return month
    def get_year(self):
        try:
            month = super(AnnouncementMonthView, self).get_year()
        except Http404:
            year = now().strftime(self.get_year_format())
        return year

    model = Announcement
    date_field = 'pub_date'
    allow_future = True

class EventMonthView(LoginRequiredMixin, MonthArchiveView):
    def get_month(self):
        try:
            month = super(EventMonthView, self).get_month()
        except Http404:
            month = now().strftime(self.get_month_format())
        return month
    def get_year(self):
        try:
            month = super(EventMonthView, self).get_year()
        except Http404:
            year = now().strftime(self.get_year_format())
        return year

    model = Event
    date_field = 'event_date'
    allow_future = True

def event_add_attendance(request, *args, **kwargs):
# def event_add_attendance(request, event_pk):
    event_pk = kwargs.get('pk')
    this_event = Event.objects.get(pk=event_pk)
    try:
        this_registration = this_event.add_user_to_list_of_attendees(user = request.user)
    except IntegrityError:
        raise Http404("You have already signed up for this event.")
    registration = get_object_or_404(EventRegistration, pk=this_registration)
    return redirect(registration)


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('announcements:login')
    template_name = 'registration/signup.html'

class EventRegistrationView(UpdateView):
    model = EventRegistration
    fields = ['number', 'note']
    # form_class = EventRegistrationForm
    success_url = reverse_lazy('announcements:show_events')
    template_name_suffix = '_update'

    # def form_valid(self, form):
    #     form.instance.created_by = self.request.user
    #     return super().form_valid(form)

templates/announcements/announcement_archive_month.html
{% extends 'base_announcements.html' %}
{% load static %}

{% block title %}Newsletter for {{ month|date:"F, Y" }} - {% endblock title %}

{% block og_title %}Newsletter for {{ month|date:"F, Y" }} - {% endblock og_title %}
{% block description %}Central Maryland Martial Arts newsletter for the month of {{ month|date:"F" }} in the year {{ month|date:"Y" }}.{% endblock description %}
{% block og_url %}{% url 'announcements:show_announcements' %}{% endblock og_url %}
{% block twitter_card %}Central Maryland Martial Arts newsletter for the month of {{ month|date:"F" }} in the year {{ month|date:"Y" }}.{% endblock twitter_card %}

{% block content %}

    <h1>Newsletter for {{ month|date:"F, Y" }}</h1>

    {% for announcement in object_list %}
        {% if pub_date != '' %}
            <b>{{ announcement.pub_date|date:"l, F j" }}:<br>
            {{ announcement.title }}</b><br>
            {{ announcement.desc }}
            {% for media in announcement.media %}
                <a href="{% static media.file_name %}" >{{ media.file_name }}</a>
            {% endfor %}<br><br>
        {% endif %}
    {% endfor %}

    <p>
        {% comment %}{% if previous_month %}
            Previous Month: {{ previous_month|date:"F Y" }}
        {% endif %}
        {% if next_month %}
            Next Month: {{ next_month|date: "F Y" }}
        {% endif %}{% endcomment %}
    </p>
{% endblock content %}

templates/announcements/event_archive.html
{% extends 'base.html' %}

{% block content %}
    <ul>
        {% for event in latest %}
            <li>{{ event.event_date }}: {{ event.title }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/announcements/event_archive_month.html
{% extends 'base_announcements.html' %}
{% load static %}

{% block title %}Events in {{ month|date:"F, Y" }} - {% endblock title %}

{% block og_title %}Events in {{ month|date:"F, Y" }} - {% endblock og_title %}
{% block description %}Central Maryland Martial Arts events for the month of {{ month|date:"F" }} in the year {{ month|date:"Y" }}.{% endblock description %}
{% block og_url %}{% url 'announcements:show_events' %}{% endblock og_url %}
{% block twitter_card %}Central Maryland Martial Arts events for the month of {{ month|date:"F" }} in the year {{ month|date:"Y" }}.{% endblock twitter_card %}

{% block content %}

    <h1>Events in {{ month|date:"F, Y" }}</h1>

    {% for event in object_list %}
        {% if event_date != '' %}
            <b>{{ event.event_date|date:"l, F j" }}:<br>
            {{ event.announcement.title }}</b><br>
            {{ event.announcement.desc }}
            {% for media in event.announcement.media %}
                <a href="{% static media.file_name %}">{{ media.file_name }}</a>
            {% endfor %}<br><br>

            <a href="{{ event.get_absolute_url }}">Sign Up!</a><br><br>
        {% endif %}
    {% endfor %}

    <p>
        {% comment %}{% if previous_month %}
            Previous Month: {{ previous_month|date:"F Y" }}
        {% endif %}
        {% if next_month %}
            Next Month: {{ next_month|date: "F Y" }}
        {% endif %}{% endcomment %}
    </p>
{% endblock content %}

templates/announcements/event_list.html
{% extends 'base.html' %}

{% block title %}  {% endblock title %}

{% block content %}
    {% for object in object_list %}
        {{ object }}<br>
    {% endfor %}
{% endblock content %}

templates/announcements/event_registration.html
{% extends 'base.html' %}

{% block title %}Register for {{ eventregistration.event }}{% endblock title %}

{% block content %}
    <h1>Register for {{ eventregistration.event }}</h1>

    <form method="POST">
        {% csrf_token %}
        {#{ form.as_p }#}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}<br><br>
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

templates/announcements/eventregistration_update.html
{% extends 'base.html' %}

{% block title %}Register for {{ eventregistration.event }}{% endblock title %}

{% block content %}
    <h1>Register for {{ eventregistration.event }}</h1>

    <form method="POST">
        {% csrf_token %}
        {#{ form.as_p }#}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}<br><br>
        {% endfor %}
        <button type="submit">Submit</button>
    </form>

{% endblock content %}

templates/base_announcements.html
{% extends 'base.html' %}

{% block submenu %}
    <a href="/">Newsletter</a> | 
    <a {#href="/events/"#}>Events</a>
{% endblock submenu %}

{% block content %}
{% endblock content %}

templates/martialarts_events/event_archive_month.html
{% extends 'base.html' %}

{% block title %}{% endblock title %}

{% block content %}

    <h1>Schedule for {{ month|date:"F, Y" }}</h1>

    {% for event in object_list %}
        <b>{{ event.event_date|date:"l, F j" }}:<br>
        {{ event.title }}</b><br>
        {{ event.desc }}<br><br>
    {% endfor %}

    <p>
        {% comment %}{% if previous_month %}
            Previous Month: {{ previous_month|date:"F Y" }}
        {% endif %}
        {% if next_month %}
            Next Month: {{ next_month|date: "F Y" }}
        {% endif %}{% endcomment %}
    </p>
{% endblock content %}